apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: timesheet-cert
  namespace: timesheet-management
spec:
  secretName: timesheet-tls-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - "172.169.37.162"
  - "timesheet-api.local"
  - "*.timesheet-api.local"
