apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timesheet-management

resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- mysql-persistent-volume.yaml
- mysql-init-configmap.yaml
- mysql-deployment.yaml
- app-deployment.yaml
- cluster-issuer.yaml
- nginx-https-direct.yaml
- https-8080-replacement.yaml
- acr-secret.yaml

images:
- name: timesheetacr.azurecr.io/timesheet-app
  newTag: latest
