apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-https-direct-config
  namespace: timesheet-management
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      upstream timesheet_backend {
        server timesheet-app-service:80;
      }
      
      server {
        listen 8080 ssl;
        server_name _;
        
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        


        location / {
          # Handle preflight OPTIONS requests
          if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://timesheet-fe-psi.vercel.app' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, HEAD, TRACE, CONNECT' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Accept-Language,Accept-Encoding,Connection,Host,Origin,Referer' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
          }
          
          proxy_pass http://timesheet_backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          # Remove CORS headers from backend response to avoid duplication
          proxy_hide_header 'Access-Control-Allow-Origin';
          proxy_hide_header 'Access-Control-Allow-Methods';
          proxy_hide_header 'Access-Control-Allow-Headers';
          proxy_hide_header 'Access-Control-Allow-Credentials';
          proxy_hide_header 'Access-Control-Expose-Headers';
          
          # Add CORS headers for all responses
          add_header 'Access-Control-Allow-Origin' 'https://timesheet-fe-psi.vercel.app' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, HEAD, TRACE, CONNECT' always;
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Accept-Language,Accept-Encoding,Connection,Host,Origin,Referer' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;
          add_header 'Access-Control-Expose-Headers' 'Authorization,Content-Type,Content-Length' always;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https-direct
  namespace: timesheet-management
  labels:
    app: nginx-https-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https-direct
  template:
    metadata:
      labels:
        app: nginx-https-direct
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tls-secret
          mountPath: /etc/nginx/ssl
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-https-direct-config
      - name: tls-secret
        secret:
          secretName: timesheet-tls-cert

